### ISSUE TITLE
Issues starting up with kickoff.sh

### ISSUE THREAD

**Issue by tur-ing** [ussjoin/reticle#2]
I have installed the image successfully! My hardware:
- Raspberry Pi B
- TP-Link TL-WN722N

About the wlan0:

``` shell
wlan0     Link encap:Ethernet  HWaddr 60:e3:27:0f:4f:e1  
          inet addr:10.137.51.223  Bcast:10.137.255.255  Mask:255.254.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:139 errors:0 dropped:0 overruns:0 frame:0
          TX packets:175 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:47399 (46.2 KiB)  TX bytes:63350 (61.8 KiB)
```

If I try to start the reticle with the `kickoff.sh` by `sudo bash kickoff.sh` I get the following output:

http://marcel-florian.de/reticle_log.txt

Does anybody know what the problem might be?

**Comment by ussjoin** [comment]
That's interesting. Does the 10.137/15 network have upstream? It looks like it's trying to run portalsmash and that's failing. Portalsmash only happens when it can't get a connection to the site it uses to test that the connection is real---it does that before it brings Tor up.

**Comment by tur-ing** [comment]
I tried to ping the 10.137.51.223 from the Pi:

``` shell
pi@raspberrypi ~ $ ping 10.137.51.223
PING 10.137.51.223 (10.137.51.223) 56(84) bytes of data.
64 bytes from 10.137.51.223: icmp_req=1 ttl=64 time=0.350 ms
64 bytes from 10.137.51.223: icmp_req=2 ttl=64 time=0.214 ms
64 bytes from 10.137.51.223: icmp_req=3 ttl=64 time=0.224 ms
64 bytes from 10.137.51.223: icmp_req=4 ttl=64 time=0.234 ms
64 bytes from 10.137.51.223: icmp_req=5 ttl=64 time=0.235 ms
64 bytes from 10.137.51.223: icmp_req=6 ttl=64 time=0.239 ms
^C
--- 10.137.51.223 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5001ms
rtt min/avg/max/mdev = 0.214/0.249/0.350/0.047 ms
```

**Comment by ussjoin** [comment]
Sorry, let me clarify. Reticle requires an Internet connection to bring its systems online, because it communicates through Tor.

**Comment by tur-ing** [comment]
OK. The Pi is connected to the router by an ethernet connection. It seems to have an active internet connection. I can ping **IP addresses** and download stuff using **IP addresses** on the Pi. But I am not able to resolve **domains**. If I want to download `wget http://marcel-florian.de/reticle_log.txt` onto the Pi for example, I have to use `wget http://129.41.139.58/reticle_log.txt` instead. The same if I try to ping sth.

I **restarted** the router and the Pi. The problem seems to continue. The new log: http://marcel-florian.de/reticle_log_1.txt

And I also took a look at the network properties: http://marcel-florian.de/ifconfig.txt

A difference that grabbed my attention: `wlan0     Interface doesn't support scanning : Device or resource busy` appears in the logs. That's funny, especially because I am using the TP-Link TL-WN722N

**Comment by ussjoin** [comment]
The Internet connection likely comes via Ethernet, rather than WiFi, and that won't really help you. The WiFi part (currently part of a _very_ odd /15 group, which seems... unlikely, though not impossible) is what's broken. The point is that Reticle isn't looking for anything over Ethernet, it's only looking over wlan0.

**Comment by tur-ing** [comment]
I have a second WiFi adapter I could use to establish an internet connection by WiFi. So I could use **wlan0** (plain adapter) to establish an internet connection and **wlan1** (the TP-Link) to monitor. Do you think that is a useful step? If yes, do you have a hint how to adjust this the best way (connecting explicitly to my router, distinction between wlan0 and wlan1, etc.)?

**Comment by ussjoin** [comment]
If you have two wlan (wlan0 and wlan1), Reticle will use wlan0 for uplink, and wlan1 for monitoring or whatnot. So that's probably what you'd like to do.

**Comment by tur-ing** [comment]
OK. I have inserted the second WiFi adapter. It is the plain one, operating as **wlan0** with MAC **00:0f:13:38:1d:85**. The TP-Link is operating as **wlan1** with MAC **60:e3:27:0f:4f:e1** (compare to http://marcel-florian.de/ifconfig_1.txt).

I still need the **ethernet connection to ssh** into the Pi ... it is not connected to the router by WiFi yet. So I get the following output: http://marcel-florian.de/reticle_log_2.txt (probably because of the missing internet connection through wlan0). 

How can I **connect wlan0 to my router** (with SSID and WPA2 key)? :satellite: The log says:

``` shell
State: start
Scanning
wlan0     Interface doesn't support scanning : Device or resource busy
```

![img_1661](https://cloud.githubusercontent.com/assets/15199933/12212717/cd532a5e-b66d-11e5-97ab-c85e8a8adec9.JPG)

**Comment by ussjoin** [comment]
https://github.com/ussjoin/portalsmash/blob/master/networks.yaml

**Comment by tur-ing** [comment]
OK. I changed **networks.yaml** to connect to my local WiFi router. That works great! :metal:

Now, **wlan0** is connected to the internet and receives packages: http://marcel-florian.de/ifconfig_2.txt
The ethernet cable is disconnected :scissors:

**wlan1** seems to be monitoring (state changed to: _monitor_), but I guess there is still something wrong: http://marcel-florian.de/reticle_log_3.txt

And the database seems to be empty:

``` shell
pi@raspberrypi ~ $ curl http://127.0.0.1:50121/reticle
{"db_name":"reticle","doc_count":4,"doc_del_count":0,"update_seq":4,"purge_seq":0,"compact_running":false,"disk_size":4194,"data_size":1700,"instance_start_time":"1452339234067876","disk_format_version":6,"committed_update_seq":4}
```

**Comment by ussjoin** [comment]
That appears to be working as expected (except that Nginx didn't bind to its port, which likely means that it was already running when you started the script). There's nothing in a base image that would add documents to the database; that's what your mission inserts do. See the example mission in the codebase for how to format one and how to insert it (to start it).
